CREATE TABLE IF NOT EXISTS "Surveys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SurveyDate" timestamp with time zone NOT NULL,
    "DistrictId" integer NOT NULL,
    "LocalBodyId" integer NOT NULL,
    "VillageId" integer NOT NULL,
    "RespondentName" text NOT NULL,
    "Age" integer NOT NULL,
    "Gender" text NOT NULL,
    "MobileNumber" text NOT NULL,
    "DevelopmentWorks" text NOT NULL,
    "Road" text NOT NULL,
    "Electricity" text NOT NULL,
    "Water" text NOT NULL,
    "Health" text NOT NULL,
    "Education" text NOT NULL,
    "GovtSchemes" text NOT NULL,
    "Satisfaction" text NOT NULL,
    "WillVote" text NOT NULL,
    "BiggestProblem" text NOT NULL,
    "Expectation" text NOT NULL,
    "Suggestion" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Surveys" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Surveys_Msr_District_DistrictId" FOREIGN KEY ("DistrictId") REFERENCES "Msr_District" ("DistrictId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Surveys_Msr_LocalBody_LocalBodyId" FOREIGN KEY ("LocalBodyId") REFERENCES "Msr_LocalBody" ("LocalBodyId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Surveys_Msr_Village_VillageId" FOREIGN KEY ("VillageId") REFERENCES "Msr_Village" ("VillageId") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Surveys_DistrictId" ON "Surveys" ("DistrictId");
CREATE INDEX IF NOT EXISTS "IX_Surveys_LocalBodyId" ON "Surveys" ("LocalBodyId");
CREATE INDEX IF NOT EXISTS "IX_Surveys_VillageId" ON "Surveys" ("VillageId");
